### PR TITLE
Restructure ingest and deliver data sections

### LINKED ISSUE #399: Docs on `ingest data` and `deliver data`
### Where's the bug?

https://www.risingwave.dev/docs/latest/intro/

### Describe the bug

I noticed that the `Ingest data` and `Deliver data` pages point to `Create Source` and `Create Sink` pages respectively. I wonder whether this is made deliberately? I think maybe we can create independent pages for `Ingest data` and `Deliver data` and explicitly mention that `Ingest data` requires invoking `create source` command. In fact, `insert into` is another way to "ingest data". Directly redirecting `Ingest data` page to `create source` page sounds like `create source` is the only way to ingest data, which is misleading.

### PR DESCRIPTION
**Pull request by hengm3467**
## Info
- **Description**: 
Refine the structure to make it easier to navigate. This is just the initial part of the revamp. For the content structural improvements and plans, see https://www.notion.so/risingwave-labs/Doc-structure-being-updated-69f507ed038848a0af2080defe7928d5

- **Related code PR**: 
[ Provide the link to the code PR here. For example, https://github.com/risingwavelabs/risingwave/pull/4085. Delete this part if there's no code PR related. ]

- **Related doc issue**: 
Resolves #399 

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: image
</details>

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

### CODE REVIEW

File: sidebars.js [hunk 1]
```diff
@@ -149,6 +132,66 @@ const sidebars = {
         },
       ]
     },
+    
+    {
+      type: 'category', 
+      label: 'Data ingestion', 
+      collapsible: true,
+      collapsed: false,
```
Comment (CharlieSYH) [inline sidebars.js]: Are we sure to expand this category by default? 
Suggestion: `collapsed: true,`
image

Comment (CharlieSYH) [inline sidebars.js]: You can add this property `link: {type: 'doc', id: 'ingestion-overview'},` to this category so that when users click on this category, it will open the overview topic.

File: sidebars.js [hunk 2]
```diff
@@ -149,6 +132,66 @@ const sidebars = {
...
+        },
+        {
+          type: 'doc',
+          label: 'Load generator',
+          id: 'create-source/create-source-datagen',
+        },
+      ]
+    },
+    {type: 'category',
+    label: 'Data delivery',
```
Comment (CharlieSYH) [inline sidebars.js:182]: You can add this property `link: {type: 'doc', id: 'delivery-overview'},` to this category so that when users click on this category, it will open the overview topic.

File: docs/ingestion-overview.md [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+- Connect to and ingest data from external sources such as databases and message brokers.
+- Insert data to tables directly.
+
+## Ingest data from external data sources
+
+### Materialized and non-materialized source connections
+
+A source is a resource that RisingWave can read data from. You can create two types of source connections in RisingWave: non-materialized and materialized source connections. The difference between these two types of connections is data from a materialized source connection is stored in RisingWave, while data from a non-materialized source is not.
+
+Use the [`CREATE SOURCE`](./sql/commands/sql-create-source.md) command to create a non-materialized source connection. After a non-materialized source connection is created, the input data is not stored in RisingWave. You need to create materialized views ([`CREATE MATERIALIXED VIEW`](./sql/commands/sql-create-mv.md)) to process the data and store the results in RisingWave.
```
Comment (CharlieSYH) [inline docs/ingestion-overview.md]: typo: ([`CREATE MATERIALIXED VIEW`]  -> ([`CREATE MATERIALIZED VIEW`]

File: docs/ingestion-overview.md [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+- [Kinesis](./create-source/create-source-kinesis.md)
+- [Pulsar](./create-source/create-source-pulsar.md)
+
+For most of the data sources, you can create either a materialized or non-materialized connection.
+
+### Supported data formats
+
+To learn about the supported data formats, see [Data formats](./sql/commands/sql-create-source.md#supported-formats).
+
+## Insert data to tables
```
Comment (CharlieSYH) [inline docs/ingestion-overview.md]: Insert data _into_?

**Review by CharlieSYH — APPROVED** [review]
